### ISSUE TITLE
Hyperform does not work with webpack

### ISSUE THREAD

**Issue by JostCrow** [hyperform/hyperform#25]
The "browser" config of hyperform does not export a module, this breaks usage in webpack and possibly other tools (like browserify):

The problem seems to be caused by pointing to the .min.js file in package.json:

```
   "browser": "dist/hyperform.min.js",
```

This file that does not export anything and thus lead to empty imports.
# Steps to reproduce:
- Install and configure webpack
- `npm install hyperform`
- `import hyperform from 'hyperform';` / var hyperform = require('hyperform');
- "hyperform" is set to an empty object
# Suggested fixes:

**1. Point to a file that exports the module:**

Changing the problem line in package.json to:

```
  "browser": "dist/hyperform.cjs.js",
```

Should resolve the issue as this file seems to export the module properly.

**2. Export the module in the minified version:**

Adding an export to the minified version should both result in a small and exported version.

**Comment by JostCrow** [comment]
@svenvandescheur

**Comment by Boldewyn** [comment]
I see. Thanks for the report! I tend towards solution 1, but have to cross-check first, that other build setups are not affected by this.

Solution 1 is favored, because I tried to provide different files for each set-up: `hyperform(.min).js` for the direct browser global, `hyperform.amd(.min).js` for AMD, `hyperform.cjs(.min).js` for CommonJS and `src/hyperform.js` for the raw ES2016 modules. So it seems, that the problem is basically caused by me misinterpreting the spec of the `browser` field.

**Comment by svenvandescheur** [comment]
I don't think the browser field is needed here as I don't see how this module is supposed to work in a non browser environment. We've tested this with webpack with the cjs versions but amd should work as well.

AMD seems to more suitable for the web. My suggestion would be to test that in webpack and browserify and if it works: ship it!

If someone wants to manually include the file they can grasp the .min.js version by hand.
