### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by jdrda** [hyperform/hyperform#41]
I suppose, that not many users want to set Hyperforms for particular form, my proposal is to autostart the Hyperform, so at the end of library initialize it with 
``hyperform(window);``
Many of libraries works like that, I think it will be much more easy for many developers.

**Comment by Boldewyn** [comment]
Thanks for the suggestion! Yes, I agree, that most of the time you probably want to simply have all forms handled. And I also agree, that if you only want to throw the library onto the page, it would be nice, if that'd "just work".

But if you do _not_ want forms to be taken over by Hyperform, you'd have a hard time to get rid of it again. Therefore it was a willful design decision to explicitly wrap forms or `window` to activate Hyperform.

There are several reasons, why you might want to take some forms off Hyperform, e.g.,

* legacy code not playing well with Hyperform taking over the whole form submission process,
* different Hyperform settings for different forms (i.e. [`prevent_implicit_submit`](https://hyperform.js.org/docs/high_level_api.html#prevent-implicit-submits) on one but not the other),
* deciding based on browser capabilities, whether to add Hyperform at all (cf. [issue 16](16))

For the time being I'll keep Hyperform's non-autoloading default. **However**, I could think of a feature like an additional attribute for Hyperform to react to, like

    ```html
    <script src="hyperform.js" data-autoload></script>
    ```

That sounds like a reasonable way to keep the library user in control of what to do. Would something like that suit your needs?

(PS: Pull requests welcome!  :grin: Otherwise it may take some time.)

**Comment by Boldewyn** [comment]
Note to implementors: How to get the current `script` element: http://www.2ality.com/2014/05/current-script.html

**Comment by jdrda** [comment]
And what about two versions - hyperform.js for normal usage and hyperform-auto.js for autostart. It is one command and duplicate files is easy. :)

**Comment by Boldewyn** [comment]
I was pondering that idea, too. I guess, when I can make peace with the thought of distributing _twelve_ files in `dist`, that would be a viable way, too :thinking:.

**Comment by jdrda** [comment]
Well, if I have a while today, I will pull the autostart with the data attribute, I am familiar with JS as you, I am primary PHP developer, so only what I need is to know how do compilation. I suppose I can create one more include for the functionality, put to master file and with having all NPM depencies installed I run NPM, is it this way? :)

**Comment by Boldewyn** [comment]
After you cloned it, it's basically this:

```sh
npm install
node_modules/.bin/jspm install
# edit src/**.js
make
# or, if you haven't got make,
node_modules/.bin/jspm build src/hyperform.js dist/hyperform.js --format global --global-name hyperform --skip-source-maps
```

For AMD and CJS packages you need to adapt the last command, cf. `Makefile`.

**Comment by Boldewyn** [comment]
I've added a [contribution guide](https://github.com/hyperform/hyperform/blob/master/CONTRIBUTING.md) now, too...

**Comment by jdrda** [comment]
Great, I will make some time for it. :)

**Comment by Boldewyn** [comment]
I've settled for an attribute `data-hf-autoload`. As of now, it's content is disregarded. If you want and your time permits, you could add support for parsing the attribute value as JSON and using it as config.
