### ISSUE TITLE
Setting "novalidateOnElements" not respected

### ISSUE THREAD

**Issue by Garbanas** [hyperform/hyperform#60]
The setting "novalidateOnElements" (default true) is not respected (in fact it is never even saved to the settings array).

When checking an element for the non-standard attribute "novalidate", the condition always evaluates to the same boolean value, rendering the attribute "novalidate" ineffective.

see pull request #61

**Comment by Boldewyn** [comment]
Thanks for the report and the pull request! You're totally right, that slipped my attention.

I've not merged your pull request, because it would have altered the meaning of this parameter. The logic is basically the other way round: If `novalidateOnElements` is `true`, skip the other tests (aka ignore any `novalidate` attribute on an element) and assume the element is a validation candidate. But I've added you as a contributor to the README. Thank you again for the report and my apologies for letting it take so long to respond.
