### ISSUE TITLE
Translations for "TextTooLong" and "TextTooShort" not working

### ISSUE THREAD

**Issue by samgarg86** [hyperform/hyperform#64]
The translations for **TextTooLong** and **TextTooShort** don't seem to work. They are always showing in english. 

<img width="1257" alt="addtranslation" src="https://user-images.githubusercontent.com/9396758/30593479-8fcdbfec-9d42-11e7-8b7b-c3edf395c3bc.png">
<img width="532" alt="wrongtranslation" src="https://user-images.githubusercontent.com/9396758/30593491-998d4b56-9d42-11e7-9799-3dd582af557e.png">

**Comment by Boldewyn** [comment]
Thanks for the report! That's a strange error, given that the loaded translation looks just fine. I'll take a look into it.

**Comment by samgarg86** [comment]
Thanks Boldewyn. I'll keep an eye on this issue. 
Do you think this could be fixed anytime soon?

**Comment by samgarg86** [comment]
Hi there, we have a task in this sprint to fix this specific bug in our checkout form. Just checking in you again, if there is any chance you might be able to fix this bug soon?

**Comment by Boldewyn** [comment]
Hm, I can't reproduce it with a simple test case:

```

**Comment by Boldewyn** [comment]
Oh, I've looked way too long at my own code to finally realize, what the problem is... :man_facepalming:

The `TextTooShort` identifier is never used but the phrase

```
"Please lengthen this text to %l characters or more (you are currently using %l characters)."
```

If you attach your translation to that phrase it should work like a charm. (Similar with TextTooLong and a couple others)

Explanation: The TextTooShort identifier is pulled automatically from Mozilla's repository, but there are other strings, that are not or not yet translated by them. This is one of them. If you compare the French translation with the German one,

https://github.com/hyperform/hyperform-l10n/blob/master/src/de.js

you see that the lower part is missing.

If you'd like to translate them (my French is close to non-existent unfortunately), I'd be very happy to merge them into the hyperform-l10n repo.

**Comment by samgarg86** [comment]
That worked like a charm, thank you!
