### ISSUE TITLE
hf-warning placement

### ISSUE THREAD

**Issue by adnanoner** [hyperform/hyperform#65]
First of all, thanks all for creating a great plugin to make use of the html5 validation API 👍 .
I use css floating labels and make use of the html order by using the input + label selector. So my html looks something like <input type="email" name="email"><label for="email">Your email</label>

I notice that Hyperform places the error message right after the input element. Is there a way to place it after the label element? Or adjust the placement?

**Comment by Boldewyn** [comment]
Yes, you can provide your own function to move the warning exactly where you want it to be. See e.g. this example: https://hyperform.js.org/examples.html#file=global_message

So, if you want to place it after the `input` parent (I assume, that's the `label`), a simple method would look like this:

```
hyperform.setRenderer('attachWarning', function(warning, element) {
  element.parentNode.appendChild(warning);
});
```

`warning` is the DOM node containing the warning, `element` is the currently evaluated `input`. Note, that you set the renderer globally for all `form`s controlled by Hyperform.

I'm keeping this ticket open, because I really should document that better in the official docs. Thanks for opening the issue.

**Comment by adnanoner** [comment]
Thanks so much! 👍

**Comment by Boldewyn** [comment]
Documented in db296ac4745d02d2c41681e01726b8e9b6eefc02.
