### ISSUE TITLE
novalidate not work

### ISSUE THREAD

**Issue by terrason** [hyperform/hyperform#77]
https://codepen.io/terrason/pen/jxeQMg

**Comment by ivuorinen** [comment]
Hi there!

`novalidate` is a [`form` level attribute][form], `input` does not have [`novalidate` attribute][input] and that's why the `required` attribute takes over the `novalidate` on your `input` name1 example.

[form]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate
[input]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes

**Comment by Boldewyn** [comment]
In principle yes, but I added a non-standard `noValidate` feature to elements: https://github.com/hyperform/hyperform/blob/master/src/tools/is_validation_candidate.js#L50-L51

Nothing too special and should work as advertised, but I can confirm terrason’s problem with my Firefox.

**Comment by Boldewyn** [comment]
I’m creating v0.9.12 right now, which will have this fixed. (An embarrassing logic error...)
