### ISSUE TITLE
Check validity of form

### ISSUE THREAD

**Issue by KeironLowe92** [hyperform/hyperform#80]
Is it possible to check the validity of the form as a whole? I've had a look through the documentation and can't find what I need. If not then I'm assuming I would have to loop through all the fields and check each one?

**Comment by Boldewyn** [comment]
Yes. You can do a

```js
hyperform.checkValidity(my_form)
```

which is basically the same as what you'd expect: https://github.com/hyperform/hyperform/blob/master/src/polyfills/checkValidity.js#L15

The canonical call is

```js
my_form.checkValidity()
```

which is supported, too, and works according to the [specification](https://www.w3.org/TR/html5/sec-forms.html#dom-htmlformelement-checkvalidity).

I'm keeping the issue open, because you're right, I haven't mentioned that in the docs, which I need to fix.

**Comment by KeironLowe92** [comment]
Thanks, unfortunately it doesn't work in my use case (which admittedly, looks like an edge case). I have a long form which I'm splitting out into chunks, I want to validate each chunk before showing the next one so my element is a div rather than a form (to avoid validating fields which aren't even displayed yet).

**Comment by Boldewyn** [comment]
HTML has you covered there, too :-)

If you can, use a `<fieldset>` for each section. Fieldsets have a `checkValidity()` method, too.
