### ISSUE TITLE
password confirm addValidator

### ISSUE THREAD

**Issue by exdeniz** [hyperform/hyperform#86]
I use setRenderer and addValidator for password.

bugs:
If type password confirm validation not show.
if typing in password in password input and have value in password confirm input,  showing standart browser error and jump focus to password confirm input.

codesandbox: https://codesandbox.io/s/ppz5zor74m

**Comment by Boldewyn** [comment]
Hi!

Thank you for the report and the test case! Yes, I can reconstruct the problem.

I assume, that it has to do with `form` not being a `<form>` but a `<div>`. That will put some of Hyperform's code on the wrong path (as it currently assumes, that it’s called with either a form or the `window` object). Quick fix for your code:

```
hyperform(q('form', form));
```

I think, it’s reasonable for Hyperform to support being called on arbitrary elements (think React components, ...). Unfortunately, as it currently stands, that’s not trivial to add, since a reasonable developer assumption is, that dynamically added forms _inside_ the wrapper should catch up the Hyperform functionality.

I’ll have to wrap my brain around how to put that into code.

**Comment by exdeniz** [comment]
Thank you for supporting the lib.
