### ISSUE TITLE
How to move validation classes from input element to parent

### ISSUE THREAD

**Issue by danbramall** [hyperform/hyperform#88]
Hi,

Firstly, thanks for this plug-in! It feels nice and light-weight and will come in very handy for simple form validation.

One issue I have, which I can't fathom from the docs, is whether it would be possible to move (or even duplicate) the validation classes (e.g. `hf-validated`, `hf-invalid` etc) from the input element to a surrounding container element instead?  I have some CSS styling that needs relies on being able to set some kind of validation status on the containers which wrap each input element rather than the inputs themselves.

Any pointers would be much appreciated.

Many thanks.

**Comment by Boldewyn** [comment]
Hi,

you have several options here. One way is to listen to `valid` and `invalid` events:

```js
myInput.addEventListener('invalid', function() {
  myInput.closest('.wrapper').classList.add('my-invalid-class');
});
myInput.addEventListener('valid', function() {
  myInput.closest('.wrapper').classList.remove('my-invalid-class');
});
```

Another, slightly more complicated method, but with more “artistic freedom” is to overwrite the rendering functions, that attach and detach the error messages, like, e.g. [in this example](https://hyperform.js.org/examples.html#file=global_message):

```js
hyperform.setRenderer('attachWarning', function(warning, element) {
  element.closest('.wrapper').classList.add('my-invalid-class');
  // the original code, copied:
  element.parentNode.insertBefore(warning, element.nextSibling);
});

hyperform.setRenderer('detachWarning', function(warning, element) {
  element.closest('.wrapper').classList.remove('my-invalid-class');
  // original code again:
  if (warning.parentNode) {
    warning.parentNode.removeChild(warning);
  }
});
```

In both cases you can also simply copy the class, since it’s already updated at that time:

```js
element.closest('.wrapper').className = element.className;
```

I hope that helps.

**Comment by danbramall** [comment]
Thanks Boldewyn, much appreciated.

**Comment by Boldewyn** [comment]
I’ve documented the first solution on https://hyperform.js.org/examples.html#file=manipulate_wrapper now.
